config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on he DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get '/home/about', to: 'homes#about'
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
 end
  resources :users, only: [:show, :edit, :update, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
   validates :title, presence: true
   validates :body, presence: true, length: {maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image
  validates :name, uniqueness: true, length: {minimum: 2, maximum: 20 }
  validates :introduction, length: {maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
   before_action :configure_permitted_parameters, if: :devise_controller?
    def after_sign_in_path_for(resource)
    user_path(current_user.id)
    end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :baria_user, only: [:edit, :destroy, :update]

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book.id)
    else
    @books = Book.all
    render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @users = @book.user
    @books = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end
  def update
    @book = Book.find(params[:id])
     if @book.update(book_params)
        flash[:notice] = "Edit successfully!"
     redirect_to book_path(@book.id)
     else
     render :edit
     end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

   private

  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end
  def baria_user
    unless Book.find(params[:id]).user.id.to_i == current_user.id
        redirect_to books_path
    end
 end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :baria_user, only:[:edit, :update]

  def show
     @user = User.find(params[:id])
     @book = Book.new
     #@books = Book.where(user_id: @user).includes(:user).order("created_at DESC")
     @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
  end

  def index
    @user = User.all
    @book = Book.new
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path(@user.id), notice:"update successfully!"
    else
    render :edit
    end

  end
end
private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction )
  end
def baria_user
    @book = User.find(params[:id])
     unless @book == current_user
     redirect_to user_path(current_user.id)
     end
 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<%= form_with model:@book, local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Update Book' %>
<% end %>
<div><%= link_to 'Show', book_path(@book.id) %></div>
<div><%= link_to 'Back', books_path %></div>

app/views/books/index.html.erb
<% if flash[:notice] %>
    <div class="flash">
         <%= flash[:notice] %>
<% end %>
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
     <% end %>
     <% end %>
<body>
  <main>
        <div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
    <%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %><table class="table">
  <tbody>
  <tr>
	  <th>name</th>
	  <th><%= current_user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= current_user.introduction %></th>
  </tr>
</tbody></table>

<div class="row">
  <%= link_to '', edit_user_path(current_user), class:"btn btn-outline-secondary btn-block fas fa-user-cog" %>

</div>
      <%= form_with model: @book, local:true do |f| %>
      <h2 class="mt-3">New book</h2>
  <div class="form-group">
    <label for="book_title">Title</label>
      <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <label for="book_opinion">Opinion</label>
    <%= f.text_area :body %>
  </div>
  <div class="form-group">
    <%= f.submit 'Create Book' %>
    <% end %>
  </div>
</form>
   </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user.id) do %>
            <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg" %>
               <% end %>
        </td>
        <td><%= link_to book_path(book.id) do %>
              <%= book.title %>
              <% end %>
        </td>
        <td><%= book.body %></td>

      </tr>
      <% end %>
  </tbody>
</table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>New book</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<%= form_with model: @book, local:true do |f| %>
  <h4>title</h4>
  <%= f.text_field :shop_name %>
  <h4>opinion</h4>
  <%= f.text_area :caption %>
  <%= f.submit '投稿' %>
<% end %>

app/views/books/show.html.erb
<% if flash[:notice] %>
    <div class="flash">
         <%= flash[:notice,] %>
<% end %>
<body>
  <main>
        <div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
    <%= attachment_image_tag @book.user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %><table class="table">
  <tbody><tr></tr>
  <tr>
	  <th>name</th>
	  <th><%= @book.user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= @book.user.introduction %></th>
  </tr>
</tbody></table>

<div class="row">
  <%= link_to '', edit_user_path(@users), class:"btn btn-outline-secondary btn-block fas fa-user-cog" %>

</div>
      <%= form_with model: @books, local:true do |f| %>
      <h2 class="mt-3">New book</h2>
  <div class="form-group">
    <label for="book_title">Title</label>
      <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <label for="book_opinion">Opinion</label>
    <%= f.text_area :body %>
  </div>
  <div class="form-group">
    <%= f.submit 'Create Book' %>
    <% end %>
  </div>
</form>
    </div>
    <div class="col-md-8 offset-md-1">
  		<h2>Book detail</h2>
  		<table class="table">
  		  <tbody><tr>
          <td>
            <%= link_to user_path(@users) do %>
            <%= attachment_image_tag @book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg" %>
              <%= @book.user.name %>
            <% end %>
           </td>
          <td>
            <%= link_to book_path(@book.id) do %>
               <%= @book.title %>
               <% end %>
          </td>
          <td><%= @book.body %></td>
          <% if @book.user_id == current_user.id %>
            <td><%= link_to 'Edit', edit_book_path(@book.id), class:"btn btn-sm btn-success edit_book" %></td>
            <td><%= link_to "Destroy", book_path(@book.id), class:"btn btn-sm btn-danger destroy_book_12788",  method: :delete,"data-confirm" => "Are you sure?" %></td>
            <% end %>
        </tr>
      </tbody></table>
    </div>
  </div>
</main>
</body>

app/views/homes/about.html.erb
<body>
<main>
        <div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>
</main>
</body>

app/views/homes/top.html.erb
<% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>
  <head>
      <meta name="csrf-param" content="authenticity_token">
      <meta name="csrf-token" content="v6fgUtW0asSN9Dn604ZmN9lQGiI1Kb4wbyA/3pHNiiH20lme9tR7OjDJTmTpRkcEye1JrdrBrsAbK4mP1cTlJw==">
      <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  </head>
  <body>
      <main>
        <div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
        </div>
      </div>
    </div>
  </div>
</div>


 </main>




</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    </head>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
          <li><%= link_to 'Home', user_path(current_user.id),class:"fas fa-home nav-link text-light" %></li>
          <a class="fas fa-users nav-link text-light" href="/users"> Users</a>
          <li><a class="fas fa-book-open nav-link text-light" href="/books"> Books</a></li>
          <li><%= link_to 'logout',destroy_user_session_path, method: :delete, class:"fas fa-sign-out-alt nav-link text-light" %></li>
          <% else %>
          <a class="fas fa-home nav-link text-light" href="/"> Home</a>
          <a class="fas fa-link nav-link text-light" href="/home/about"> About</a>
          <li><%= link_to 'sign up', new_user_registration_path, class:"fas fa-user-plus nav-link text-light" %></li>
          <li><a class="fas fa-sign-in-alt nav-link text-light" href="/users/sign_in"> login</a></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>
 <main class="mb-auto">
    <%= yield %>
 </main>
    <footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		 <p>CopyRight Infratop.inc</p>
    		</div>
    	</div>
    </div>
  </div>
</footer>
  </body>
</html>

app/views/users/edit.html.erb
<h2>User info</h2>
<% if @user.errors.any? %>
  <%= @user.errors.count %>error prohibited this obj from being saved
  <% @user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<%= form_with model:@user, local:true do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
  <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
  <label for="inputImage">ProfileImage</label>
  <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
  <label for="inputIntroduction">Introduction</label>
  <%= f.text_field :introduction, autofocus: true, id:"inputIntroduction", placeholder:"自己紹介"%>
  <%= f.submit "Update User" %>
<% end %>

app/views/users/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
     <% end %>
<% end %>
<body>
  <main>
        <div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
    <%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %><table class="table">
  <tbody>
  <tr>
	  <th>name</th>
	  <th><%= current_user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= current_user.introduction %></th>
  </tr>
</tbody></table>

<div class="row">
  <%= link_to '', edit_user_path(current_user), class:"btn btn-outline-secondary btn-block fas fa-user-cog" %>

</div>
      <%= form_with model: @book, local:true do |f| %>
      <h2 class="mt-3">New book</h2>
  <div class="form-group">
    <label for="book_title">Title</label>
      <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <label for="book_opinion">Opinion</label>
    <%= f.text_area :body %>
  </div>
  <div class="form-group">
    <%= f.submit 'Create Book' %>
    <% end %>
  </div>
</form>
 </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>


      <table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
  <% @user.each do |user| %>
      <tr>
        <td>
            <%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg" %>
        </td>
        <td>
            <%= user.name %>
        </td>
         <td><%= link_to 'Show', user_path(user.id), class:"btn btn-sm btn-success edit_book" %></td>
      </tr>
      <% end %>
  </tbody>
</table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>

<body>
  <main>
    <div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
    <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %><table class="table">
  <tbody><tr></tr>
  <tr>
	  <th>name</th>
	  <th><%= @user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= @user.introduction %></th>
  </tr>
</tbody></table>

<div class="row">
  <%= link_to '', edit_user_path(@user), class:"btn btn-outline-secondary btn-block fas fa-user-cog" %>

</div>
      <%= form_with model: @book, local:true do |f| %>
      <h2 class="mt-3">New book</h2>
  <div class="form-group">
    <label for="book_title">Title</label>
      <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <label for="book_opinion">Opinion</label>
    <%= f.text_area :body %>
  </div>
  <div class="form-group">
    <%= f.submit 'Create Book' %>
    <% end %>
  </div>
</form>

    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user.id) do %>
            <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg" %>
               <% end %>
        </td>
        <td><%= link_to book_path(book.id) do %>
              <%= book.title %>
              <% end %>
        </td>
        <td><%= book.body %></td>
      </tr>
      <% end %>
  </tbody>
</table>
    </div>
  </div>
</div>